### ISSUE TITLE
Getting "can't convert String into Integer" errors on git_webhook and git_deploy_key

### ISSUE THREAD

**Issue by aharden** [abrader/abrader-gms#10]
Trying to automate r10k-related SSH keys and webhooks in our PE 3.7/3.8 environment that has control repos on GitHub Enterprise.  Both git_deploy_key and git_webhook return "Could not evaluate: can't convert String into Integer" with the following code (anonymized):

    git_deploy_key { 'r10k_add_deploy_key_to_puppet_control_repo':
      ensure       => present,
      name         => $::fqdn,
      path         => '/root/.ssh/id_rsa.pub',
      token        => '65ba6770857c9f29d76ba5149da2c697fb39827e',
      project_name => 'Puppetdev/control',
      server_url   => 'https://github.example.net/api/v3',
      provider     => 'github',
    }
    git_webhook { 'r10k_post_receive_webhook' :
      ensure             => present,
      webhook_url        => 'https://puppet:puppet@puppet.example.net:8088/payload',
      token              => '65ba6770857c9f29d76ba5149da2c697fb39827e',
      project_name       => 'Puppetdev/control',
      server_url         => 'https://github.example.net/api/v3',
      disable_ssl_verify => true,
      provider           => 'github',
    }

Grateful for any pointers.  I'm not good enough with Ruby yet to try to debug the types and providers.

**Comment by abrader** [comment]
As posted, I am not able to replicate the issue mentioned.  Can you post your Puppet run output with the --verbose --debug --trace options enabled?

**Comment by aharden** [comment]
Good thought.  Here are the relevant lines from the catalog run pertaining to the two errors.  This is on a PE 3.8.1 monolithic server.  Let me know if you need more of the agent run log.

Error: /Stage[main]/Te_puppet::Master::Ca/Git_deploy_key[r10k_add_deploy_key_to_puppet_control_repo]: Could not evaluate: can't convert String into Integer
/var/opt/lib/pe-puppet/lib/puppet/provider/git_deploy_key/github.rb:60:in `[]'
/var/opt/lib/pe-puppet/lib/puppet/provider/git_deploy_key/github.rb:60:in `block in exists?'
/var/opt/lib/pe-puppet/lib/puppet/provider/git_deploy_key/github.rb:59:in `each'
/var/opt/lib/pe-puppet/lib/puppet/provider/git_deploy_key/github.rb:59:in `exists?'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/property/ensure.rb:81:in `retrieve'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:1048:in `retrieve'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:1076:in `retrieve_resource'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction/resource_harness.rb:236:in `from_resource'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction/resource_harness.rb:19:in `evaluate'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:204:in `apply'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:217:in `eval_resource'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:147:in `call'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:147:in `block (2 levels) in evaluate'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:327:in `block in thinmark'
/opt/puppet/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:326:in `thinmark'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:147:in `block in evaluate'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/graph/relationship_graph.rb:118:in `traverse'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:138:in `evaluate'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:169:in `block in apply'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/log.rb:149:in `with_destination'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction/report.rb:112:in `as_logging_destination'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:168:in `apply'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:120:in `block in apply_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:161:in `block in benchmark'
/opt/puppet/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:160:in `benchmark'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:119:in `apply_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:227:in `run_internal'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:134:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/context.rb:64:in `override'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet.rb:244:in `override'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:133:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:47:in `block (4 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent/locker.rb:20:in `lock'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:47:in `block (3 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:117:in `with_client'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:44:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:82:in `run_in_fork'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:43:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `call'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `controlled_run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:41:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:361:in `onetime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:327:in `run_command'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:507:in `plugin_hook'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:488:in `exit_on_fail'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:146:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:92:in `execute'
/opt/puppet/bin/puppet:8:in `<main>'
Error: /Stage[main]/Te_puppet::Master::Ca/Git_webhook[r10k_post_receive_webhook]: Could not evaluate: can't convert String into Integer
/var/opt/lib/pe-puppet/lib/puppet/provider/git_webhook/github.rb:59:in `[]'
/var/opt/lib/pe-puppet/lib/puppet/provider/git_webhook/github.rb:59:in `block in exists?'
/var/opt/lib/pe-puppet/lib/puppet/provider/git_webhook/github.rb:58:in `each'
/var/opt/lib/pe-puppet/lib/puppet/provider/git_webhook/github.rb:58:in `exists?'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/property/ensure.rb:81:in `retrieve'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:1048:in `retrieve'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type.rb:1076:in `retrieve_resource'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction/resource_harness.rb:236:in `from_resource'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction/resource_harness.rb:19:in `evaluate'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:204:in `apply'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:217:in `eval_resource'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:147:in `call'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:147:in `block (2 levels) in evaluate'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:327:in `block in thinmark'
/opt/puppet/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:326:in `thinmark'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:147:in `block in evaluate'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/graph/relationship_graph.rb:118:in `traverse'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction.rb:138:in `evaluate'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:169:in `block in apply'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/log.rb:149:in `with_destination'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/transaction/report.rb:112:in `as_logging_destination'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource/catalog.rb:168:in `apply'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:120:in `block in apply_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:161:in `block in benchmark'
/opt/puppet/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:160:in `benchmark'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:119:in `apply_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:227:in `run_internal'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:134:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/context.rb:64:in `override'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet.rb:244:in `override'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:133:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:47:in `block (4 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent/locker.rb:20:in `lock'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:47:in `block (3 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:117:in `with_client'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:44:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:82:in `run_in_fork'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:43:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `call'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `controlled_run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:41:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:361:in `onetime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:327:in `run_command'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:507:in `plugin_hook'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:488:in `exit_on_fail'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:381:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:146:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:92:in `execute'
/opt/puppet/bin/puppet:8:in `<main>'

Thanks!

**Comment by mvisonneau** [comment]
I have the same behaviour unfortunately :(

**Comment by aharden** [comment]
Thanks for confirming, @mvisonneau.

**Comment by mvisonneau** [comment]
You're welcome..! For my part I am using OSE and Gitlab though.

```
Error: /Stage[main]/Main/Git_deploy_key[add_deploy_key_to_puppet_control]: Could not evaluate: can't convert String into Integer
/etc/puppet/modules/gms/lib/puppet/provider/git_deploy_key/gitlab.rb:60:in `[]'
/etc/puppet/modules/gms/lib/puppet/provider/git_deploy_key/gitlab.rb:60:in `block in exists?'
/etc/puppet/modules/gms/lib/puppet/provider/git_deploy_key/gitlab.rb:59:in `each'
/etc/puppet/modules/gms/lib/puppet/provider/git_deploy_key/gitlab.rb:59:in `exists?'
/usr/lib/ruby/vendor_ruby/puppet/property/ensure.rb:81:in `retrieve'
/usr/lib/ruby/vendor_ruby/puppet/type.rb:1048:in `retrieve'
/usr/lib/ruby/vendor_ruby/puppet/type.rb:1076:in `retrieve_resource'
/usr/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:236:in `from_resource'
/usr/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:19:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/transaction.rb:204:in `apply'
/usr/lib/ruby/vendor_ruby/puppet/transaction.rb:217:in `eval_resource'
/usr/lib/ruby/vendor_ruby/puppet/transaction.rb:147:in `call'
/usr/lib/ruby/vendor_ruby/puppet/transaction.rb:147:in `block (2 levels) in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:327:in `block in thinmark'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:326:in `thinmark'
/usr/lib/ruby/vendor_ruby/puppet/transaction.rb:147:in `block in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:118:in `traverse'
/usr/lib/ruby/vendor_ruby/puppet/transaction.rb:138:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:169:in `block in apply'
/usr/lib/ruby/vendor_ruby/puppet/util/log.rb:149:in `with_destination'
/usr/lib/ruby/vendor_ruby/puppet/transaction/report.rb:112:in `as_logging_destination'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:168:in `apply'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:120:in `block in apply_catalog'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:161:in `block in benchmark'
  sr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
▽usr/lib/ruby/vendor_ruby/puppet/util.rb:160:in `benchmark'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:119:in `apply_catalog'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:227:in `run_internal'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:134:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
/usr/lib/ruby/vendor_ruby/puppet.rb:244:in `override'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:133:in `run'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:302:in `apply_catalog'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:236:in `block in main'
/usr/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
/usr/lib/ruby/vendor_ruby/puppet.rb:244:in `override'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:198:in `main'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:159:in `run_command'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block (2 levels) in run'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:507:in `plugin_hook'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:488:in `exit_on_fail'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:146:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:92:in `execute'
/usr/bin/puppet:8:in `<main>'
```

**Comment by mvisonneau** [comment]
I suspect a SSL certificate issue on my side.

**Comment by abrader** [comment]
@mvisonneau That is a fair comment and I will look into provided such an error.  Thanks for the input.  @aharden no chance this could also be your issue?

**Comment by aharden** [comment]
@abrader Yes, I think we're on to something.  My GHE server uses a cert signed by our company's internal CA (unrelated to Puppet Enterprise deployment CA).

**Comment by aharden** [comment]
I'm figuring out how to proactively add our CA's cert to the puppet master's root certificates (running Ubuntu 14.04).  I'm thinking that might help the issue.

**Comment by aharden** [comment]
I added our internal CA to the OS's root certificate store using the pcfens/ca_cert module and restart the pe-puppetserver service.  That didn't affect this condition.  I don't know if there's a more appropriate way to add support for our CA to this process.

**Comment by abrader** [comment]
@aharden I'll work on integrating auth testing into the providers with debugging output provided.  This will probably be the best way to rule out an issue with the module.

**Comment by aharden** [comment]
OK, thanks!

**Comment by abrader** [comment]
@mvisonneau @aharden Latest release of this module has Stash support and debugging heavily embedded: https://forge.puppetlabs.com/abrader/gms
