### ISSUE TITLE
I should not be required to use a fqdn for my gms server, I would like to use the short name

### ISSUE THREAD

**Issue by npwalker** [abrader/abrader-gms#13]
https://github.com/abrader/abrader-gms/blob/fd47b54579aaf80b2c9514cc0de861a3963629b4/lib/puppet/type/git_deploy_key.rb#L49-L50

**Comment by abrader** [comment]
You are correct sir, FQDN should not be required.  I'll get cracking...

**Comment by abrader** [comment]
Fixed.  This is the updated regex: https://github.com/abrader/abrader-gms/blob/master/lib/puppet/type/git_webhook.rb#L36

I will cut a release this week with other very necessary updates.
