### ISSUE TITLE
Update documentation for GitLab user minimum permissons

### ISSUE THREAD

**Issue by natemccurdy** [abrader/abrader-gms#14]
In order for the GitLab token to be able to create deploy keys, the associated user must be a 'master' or 'owner' on the GitLab server.

See: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/permissions/permissions.md#permissions

**Comment by abrader** [comment]
Now included in the top of the README: https://github.com/abrader/abrader-gms/blob/master/README.md
