### ISSUE TITLE
Add parameter for disabling SSL verification

### ISSUE THREAD

**Issue by acidprime** [abrader/abrader-gms#3]
For r10k users who use the ssl webhook , they will need to disable ssl verification on github to make use of this t&p when using their control repository 

I think this is done with the config blob
https://developer.github.com/v3/repos/hooks/#edit-a-hook

**Comment by abrader** [comment]
Added 'disable_ssl_verify' parameter per your request

Please test this commit to see if this resolves this issue/request:

https://github.com/abrader/abrader-gms/commit/04118814ef61a5cdd9b5ad7dd6ae1188b9a404e1

If all is good, I will tag a release and post to the forge.

**Comment by acidprime** [comment]
@abrader :+1: worked for me after hacking around #5

**Comment by abrader** [comment]
I'll work https://github.com/abrader/abrader-gms/issues/5 into the code now.  I'll get to https://github.com/abrader/abrader-gms/issues/6 tonight.  Forge release thereafter.  Thanks as always.

**Comment by abrader** [comment]
v0.0.6 (including this params) now available: https://forge.puppetlabs.com/abrader/gms
