### ISSUE TITLE
missing tag 1.0.3

### ISSUE THREAD

**Issue by rjhornsby** [abrader/abrader-gms#32]
I'm having a hard time debugging an issue with gms, and it's a little more confusing because there's no 1.0.3 tag. It appears that 1.0.3 is (presently) the master/HEAD as per metadata.json.

Could you please tag the appropriate commit with 1.0.3?

thanks

**Comment by abrader** [comment]
https://github.com/abrader/abrader-gms/releases/tag/v1.0.3
👍
