### ISSUE TITLE
Errors with GitLab 8.15

### ISSUE THREAD

**Issue by pioto** [abrader/abrader-gms#36]
After upgrading GitLab to 8.15, I'm now getting this error from the `git_deploy_key` and `git_webhook` calls in [`pe_code_manager_webhook::code_manager`](https://github.com/npwalker/pe_code_manager_webhook):

```
Could not evaluate: no implicit conversion of String into Integer
```

I've checked, and my API key hasn't changed, so it seems like possibly some API change is breaking things?

**Comment by pioto** [comment]
Hrm, it seems that, in my attempt to diagnose this error, it has gone away. I think the resolution may have been to "impersonate" the GitLab user in question; after that, the API seemed to work?

**Comment by abrader** [comment]
@pioto Interesting.  Closing this one for now but if you don't mind I'll be in touch to get your experiences moving forward.
