### ISSUE TITLE
http URL validation is too restrictive

### ISSUE THREAD

**Issue by acidprime** [abrader/abrader-gms#5]
The regex here:

https://github.com/abrader/abrader-gms/blob/master/lib/puppet/type/git_webhook.rb#L36

will fail if someone uses http://user:password@server:8080/payload

I am wondering is something more like 

`^(https?:\/\/).*:?.*\/?$` would still work but not be as finicky with possible permutations

**Comment by acidprime** [comment]
example error for people who search

```shell
Error: Failed to apply catalog: Parameter webhook_url failed on Git_webhook[puppet_webhook]: Git webhook URL must be fully qualified, not 'https://puppet:im-a-password@ice.wallcity.org:8088/payload' at /etc/puppetlabs/puppet/environments/production/site/profile/manifests/master.pp:12
Wrapped exception:
Git webhook URL must be fully qualified, not 'https://puppet:im-a-password@ice.wallcity.org:8088/payload'
```

**Comment by abrader** [comment]
Weakened the validation per your suggest, as seen in this commit: https://github.com/abrader/abrader-gms/commit/61def084caf1fbd8c620dee63be9ec5139336c0a

**Comment by abrader** [comment]
Or...rather this commit: https://github.com/abrader/abrader-gms/commit/9ae51c141db808e5a3b83f4c48fee9e7e952e61d

**Comment by acidprime** [comment]
yeah I found it ;)

**Comment by oznah** [comment]
I am still getting error: 

`Failed to apply catalog: Parameter webhook_url failed on Git_webhook[web_post_receive_webhook]: Git webhook URL must be fully qualified, not 'puppet:puppet@fqdn.puppetmaster.com:8088/payload' at /etc/puppetlabs/puppet/environments/production/modules/profiles/manifests/r10k.pp:113 Wrapped exception: Git webhook URL must be fully qualified, not 'puppet:puppet@fqdn.puppetmaster.com:8088/payload'`

- zack/r10k, 2.6.5
- abrader/gms, 0.0.6

r10k code

```
 git_webhook { 'web_post_receive_webhook' :
    ensure             => present,
    webhook_url        => 'https://puppet:puppet@fqdn.puppetmaster.com:8088/payload',
    token              =>  hiera('gitlab_api_token'),
    project_name       => 'puppet/control',
    server_url         => 'https://fqdn.gitlab.com',
    disable_ssl_verify => true,
    provider           => 'gitlab',
}
```

Shouldn't matter but, I'm using gitlab.

**Comment by abrader** [comment]
My apologies for the delay.  Confirmed the issue.  Thanks for the submission.  I will be getting to the refactoring of the regex shortly.

**Comment by abrader** [comment]
@oznah Please try the validation from this release: https://github.com/abrader/abrader-gms/blob/master/lib/puppet/type/git_webhook.rb#L36

Worked for me, would like your input.

**Comment by oznah** [comment]
I will give it a try tomorrow.

**Comment by abrader** [comment]
Confirmed with other interested parties this is now working for them as well.  Committed changes to a new forge release v.0.0.8: https://forgeapi.puppetlabs.com/v3/files/abrader-gms-0.0.8.tar.gz

**Comment by oznah** [comment]
Sorry for the delay. I confirmed that this is working now. No more error.

**Comment by abrader** [comment]
No worries.  Thanks for checking.
