### ISSUE TITLE
Access token requirements should be documented

### ISSUE THREAD

**Issue by acidprime** [abrader/abrader-gms#6]
I think it would helpful to have a quick note for at least github that you can create access tokens with limited abilities for security to accomplish only webhooks 

see this screen shot
![screen shot 2015-02-24 at 11 07 08 am](https://cloud.githubusercontent.com/assets/1173142/6358363/d348bc06-bc1f-11e4-81e4-7b137089a680.png)

**Comment by abrader** [comment]
Updated https://github.com/abrader/abrader-gms/blob/master/README.md w/ instructions on how to create an access token with limited access rights to webhook management.
