### ISSUE TITLE
0.0.8 tarball has bum permissions on git_webhook.rb

### ISSUE THREAD

**Issue by bhechinger** [abrader/abrader-gms#7]
When installing this from the forge git_webhook.rb ends up being 400 which makes puppet unhappy. Looking in the tarball it's 600 which really isn't any better.

Would you mind rolling a new tarball with the correct permissions on that file?

Thanks!

**Comment by abrader** [comment]
Sure enough:

-rw-r--r--@ 1 abrader  staff   2.0K Feb 24 11:18 git_deploy_key.rb
-rw-------@ 1 abrader  staff   2.8K Apr 16 15:43 git_webhook.rb

Fixing now...

**Comment by abrader** [comment]
Fixed!

tar -zxf abrader-gms-0.0.9.tar.gz
cd abrader-gms-0.0.9
ls

-rw-r--r--  1 abrader  staff   2.0K Jun 12 15:37 git_deploy_key.rb
-rw-r--r--  1 abrader  staff   2.8K Jun 12 15:37 git_webhook.rb
